-- MySQL Script generated by MySQL Workbench
-- 10/19/18 16:44:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sonic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `type` ;

CREATE TABLE IF NOT EXISTS `type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL COMMENT 'Le nom du type',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'La date de création du type',
  `updated_at` TIMESTAMP NULL COMMENT 'La date de la dernière mise à jour du type',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `character`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character` ;

CREATE TABLE IF NOT EXISTS `character` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL COMMENT 'Le nom du personnage',
  `description` TEXT NULL COMMENT 'La description du personnage',
  `picture` VARCHAR(128) NULL COMMENT 'L\'URL de l\'image du personnage',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'La date de création du personnage',
  `updated_at` TIMESTAMP NULL COMMENT 'La date de la dernière mise à jour du personnage',
  `type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_character_type_idx` (`type_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `type`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `type` (`id`, `name`, `created_at`, `updated_at`) VALUES (1, 'Gentils', DEFAULT, NULL);
INSERT INTO `type` (`id`, `name`, `created_at`, `updated_at`) VALUES (2, 'Méchants', DEFAULT, NULL);
INSERT INTO `type` (`id`, `name`, `created_at`, `updated_at`) VALUES (3, 'Développeurs', DEFAULT, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `character`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `character` (`id`, `name`, `description`, `picture`, `created_at`, `updated_at`, `type_id`) VALUES (1, 'Sonic', 'Sonic est un herrisson supersonique le plus rapide du monde. Toujours en vadrouille, il va où le vent l’emporte et vit sa vie selon ses propres règles plutôt que celles de ceux qui l’entourent. Il est plutôt facile à vivre et aide toujours son prochain. Ce qu’il déteste plus que tout c’est Dr Eggman qui veut prendre le controle du monde.', 'sonic.jpg', '2018-10-20 15:00:00', NULL, 1);
INSERT INTO `character` (`id`, `name`, `description`, `picture`, `created_at`, `updated_at`, `type_id`) VALUES (2, 'Amy Rose', 'Amy Rose est une fille excessivement joyeuse et très amoureuse de Sonic et veut se marier avec lui. Elle se sert de son Piko Piko Hammer pour se battre. Sonic l’a trouve plus ou moins embarrassante mais au fond de lui , il ne la déteste peut-être pas tant que ça.', 'amy.jpg', '2018-10-20 15:00:00', NULL, 1);
INSERT INTO `character` (`id`, `name`, `description`, `picture`, `created_at`, `updated_at`, `type_id`) VALUES (3, 'Tails', 'Miles « Tails » Prower surnommé Tails est un renard à deux queues est un véritable fou de la mécanique et ces compétences sont égale du méchant Dr Egmann. Il fait toujours de son mieux pour aider Sonic, qui le considère plus ou moins comme son petit frère.', 'tails.jpg', '2018-10-20 15:00:00', NULL, 1);
INSERT INTO `character` (`id`, `name`, `description`, `picture`, `created_at`, `updated_at`, `type_id`) VALUES (4, 'Knuckles', 'Knuckles est un échidné égoïste avec des dreadlocks de l’île de l’Ange. Il a été nommé gardien de la Master Emerauld. Il est dur, têtu et inflexible. Il se considère être le rival de Sonic, pefut-être parce qu’il rêve d’un mode de vie plus libre. Il est également chasseur de trésors et compétent en arts martiaux.', 'knuckles.jpg', '2018-10-20 15:00:00', NULL, 2);
INSERT INTO `character` (`id`, `name`, `description`, `picture`, `created_at`, `updated_at`, `type_id`) VALUES (5, 'Cream', 'Cream est une mignonne petite lapine qui emmène son minuscule Chao « Cheese » avec elle partout. Elevée comme une princesse, elle est un peu naïve et parfois simplette, et elle se laisse souvent wmbarquer dans les problèmes des autres. Elle aime aussi les glaces.', 'cream.jpg', '2018-10-20 15:00:00', NULL, 1);
INSERT INTO `character` (`id`, `name`, `description`, `picture`, `created_at`, `updated_at`, `type_id`) VALUES (6, 'Big', 'Big le chat est un énorme felin qui vit dans la paix et la tranquillité avec son meilleur ami Froggy, au milieu de la jungle. Son passe-temps préféré et la pêche. Il est fort mais doux et très relax. il fais tout son possible pour aider ses amis.', 'big.jpg', '2018-10-20 15:00:00', NULL, 1);
INSERT INTO `character` (`id`, `name`, `description`, `picture`, `created_at`, `updated_at`, `type_id`) VALUES (7, 'Shadow', 'Shadow le hérisson noir est la sinistre incarnation de Sonic crée par Gérald Robotnik. il vieillit jamait et peut utiliser une technique appelée « Chaos Control » pour fausser le tenmps et l’espace.', 'shadow.jpg', '2018-10-20 15:00:00', NULL, 2);
INSERT INTO `character` (`id`, `name`, `description`, `picture`, `created_at`, `updated_at`, `type_id`) VALUES (8, 'E-123 Omega', 'E-123 Omega est le dernier et le plus puissant des robots de la série E du Dr Egmann. Omega a été réactivé accidentellement par Rouge alors qu’elle libérait Shadow. A partir de ce momen-là, Omega a décidé de détruire toutes les machine du Dr Egmann pour se venger de lui.', 'e123.jpg', '2018-10-20 15:00:00', NULL, 2);
INSERT INTO `character` (`id`, `name`, `description`, `picture`, `created_at`, `updated_at`, `type_id`) VALUES (9, 'Rouge', 'Rouge est une chauve souris qui est une chasseuse de trésors professionnelle, toujours en quête de pierres les plus précieuses au monde. C’est également une espionne du gouvernement à temps partiel. Intrépide, ravissante et débordante de charme féminin, ellese dévoue son travail.qu’elle fait jusqu’au bout.', 'rouge.jpg', '2018-10-20 15:00:00', NULL, 1);
INSERT INTO `character` (`id`, `name`, `description`, `picture`, `created_at`, `updated_at`, `type_id`) VALUES (10, 'Espio', 'Espio le caméléon dogmatique et imbu de sa personne qui travaille à l’agence de détectives Chaotix. Il a une discipline militariste en dépit d’être tranquille et désinvolte, et grâce à sa formation ninja, il peut faire face aux problèmes sans se soucier du danger.', 'espio.jpg', '2018-10-20 15:00:00', NULL, 1);
INSERT INTO `character` (`id`, `name`, `description`, `picture`, `created_at`, `updated_at`, `type_id`) VALUES (11, 'Vector', 'Vector le crocodile détective hors-la-loi et boss de l’agence de détective Chaotix. Il peut trouver des solutions pacifiques aux problèmes qui se posent à lui, du moment qu’il n’est pas possible de trouver une méthode agressive.', 'vector.jpg', '2018-10-20 15:00:00', NULL, 1);
INSERT INTO `character` (`id`, `name`, `description`, `picture`, `created_at`, `updated_at`, `type_id`) VALUES (12, 'Charmy', 'Charmy l’abeille est un gosse amusant et étourdi adore faire le pitre et donne l’impression que le reste du personnel de Chaotix est professionnel. Il est généralement de bonne humeur et allègre mais lorsqu’il se met en colère il a tendance à canaliser la source de cette colère dans sa queue piquante.', 'charmy.jpg', '2018-10-20 15:00:00', NULL, 1);
INSERT INTO `character` (`id`, `name`, `description`, `picture`, `created_at`, `updated_at`, `type_id`) VALUES (13, 'Dr. Egmann', 'Dr. Egmann est un docteur qui a QI extraordinaire de 300. Egmann est un romantique, un féministe et il se veut être gentilhomme. Malheureusement, son charme est difficuile à percevoir à travers l’abominable rire qui accompagne ses folles déclarations de suprématie mondiale. Sonic essaie de trouver un moyen de mettre fin à ses stratagèmes.', 'eggman.jpg', '2018-10-20 15:00:00', NULL, 2);

COMMIT;

